### ISSUE TITLE
Where '/content/drive/My Drive/Deepbind/best_hyperpamarameters_2.pth' came from

### ISSUE THREAD

**Issue by Lesley96** [MohamedChaabane2/DeepBind-with-PyTorch#1]
I'm wondering where '/content/drive/My Drive/Deepbind/best_hyperpamarameters_2.pth' came from, is it a copy file of best_hyperpamarameters.pth? Thanks.

**Comment by MedChaabane** [comment]
yes you can consider it as just a copy file. In my first code, I was running the whole code for 2 datasets in parallel so I was using '/content/drive/My Drive/Deepbind/best_hyperpamarameters.pth' for the first dataset and '/content/drive/My Drive/Deepbind/best_hyperpamarameters_2.pth' for the second dataset. 
I fixed now the code, so you can run the code with no issues. Thanks.

**Comment by Lesley96** [comment]
I got it, thanks a lot.
